/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tetris;

import junit.framework.TestSuite;
import org.junit.jupiter.api.*;
import static org.junit.Assert.*;
import tetris.model.GameModelTest;
public class AppTest {

}
